fix eclipse-lombok knowledge: - remove `-Xbootclasspath` lombok from eclipse.ini due to java.lang.NoClassDefFoundError: javax/annotation/processing/AbstractProcessor on JDK9+ - add MANIFEST.MF files for keeping source/test folders